
sudo: false

language: python
python:

  - 3.6

# Install the codecov pip dependency
install:
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls

# Run the unit test
script:
  - pytest --cov=log.py/
# Push the results back to codecov
after_success:
  - coveralls
