language: python
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - pypy3

before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
  - pip install coveralls

install:
  - coverage run --source=mypkg -m pytest tests/
  - pip install tox-travis

script: tox

after_success:
  - coveralls

